/* eslint-env node */
var path = require('path');

var createRedirectPage = function(destination) {
  // Make sure path is absolute
  var href = destination[0] === '/' ? destination : '/' + destination;

  // Minimal, but valid, HTML
  return `<!doctype html><meta http-equiv=refresh content="0; url=${href}"><link rel=canonical href="${href}"><title>Page Moved</title>New location: <a href="${href}">${href}</a>`;
};

var NETLIFY_REDIRECTS_FILE_PATH = '_redirects';

module.exports = function(options) {
  return function(files, metalsmith, done) {
    const aliases = ['# DO NOT EDIT: Autogenerated by metalsmith-alias'];
    for (let file in files) {
      const data = files[file];

      if (!('alias' in data)) {
        continue;
      }

      const destination = 'path' in data ? data.path : file;
      const redirectPage = {
        contents: new Buffer(createRedirectPage(destination)),
      };

      data.alias.forEach(alias => {
        if (!path.extname(alias)) {
          alias = path.join(alias, 'index.html');
        }

        // Don't overwrite if already exists
        if (!(alias in files)) {
          files[alias] = Object.assign(
            {
              path: alias,
            },
            redirectPage,
          );
        }

        if (options.netlify) {
          aliases.push(`/${alias}  /${destination === '/' ? '' : destination}`);
        }
      });
    }

    if (options.netlify) {
      files[NETLIFY_REDIRECTS_FILE_PATH] = {
        path: NETLIFY_REDIRECTS_FILE_PATH,
        contents: new Buffer(aliases.join('\n')),
      };
    }

    setImmediate(done);
  };
};
