const assert = require('assert');

const alias = require('./index')({netlify: true});

const files = {
  'about/index.html': {
    alias: ['foo', 'bar', 'baz'],
  },
  'baz/index.html': {
    original: true,
  },
  'has/path.html': {
    path: 'real_path',
    alias: ['old/path.jpg'],
  },
};

alias(files, {}, () => {
  assert('foo/index.html' in files);
  assert('bar/index.html' in files);

  assert(files['baz/index.html'].original, 'Page not overwritten by alias');

  assert('old/path.jpg' in files, 'extension not appended if present in alias');
  assert(
    /real_path/.test(files['old/path.jpg'].contents.toString()),
    '.path used if present',
  );

  assert('_redirects' in files, '_redirects file created');
  assert.equal(
    files['_redirects'].contents.toString(),
    `# DO NOT EDIT: Autogenerated by metalsmith-alias
/foo/index.html  /about/index.html 301!
/foo/  /about/index.html 301!
/foo  /about/index.html 301!
/bar/index.html  /about/index.html 301!
/bar/  /about/index.html 301!
/bar  /about/index.html 301!
/baz/index.html  /about/index.html 301!
/baz/  /about/index.html 301!
/baz  /about/index.html 301!
/old/path.jpg  /real_path 301!`,
  );
});
